import useIsPhoneX from './useIsPhoneX';

export {
  default as createMemo,
  default as createReducerContext,
  default as createReducer,
  default as createStateContext,
  default as useAsync,
  default as useAsyncFn,
  default as useAsyncRetry,
  default as useAudio,
  default as useBattery,
  default as useBeforeUnload,
  default as useBoolean,
  default as useClickAway,
  default as useCookie,
  default as useCopyToClipboard,
  default as useCounter,
  default as useCss,
  default as useCustomCompareEffect,
  default as useDebounce,
  default as useDeepCompareEffect,
  default as useDefault,
  default as useDrop,
  default as useDropArea,
  default as useEffectOnce,
  default as useEnsuredForwardedRef, ensuredForwardRef,
  default as useEvent,
  default as useError,
  default as useFavicon,
  default as useFullscreen,
  default as useGeolocation,
  default as useGetSet,
  default as useGetSetState,
  default as useHarmonicIntervalFn,
  default as useHover,
  default as useHoverDirty,
  default as useIdle,
  default as useIntersection,
  default as useInterval,
  default as useIsomorphicLayoutEffect,
  default as useKey,
  default as createBreakpoint,
  default as useKeyPress,
  default as useKeyPressEvent,
  default as useLatest,
  default as useLifecycles,
  default as useList,
  default as useLocalStorage,
  default as useLocation,
  default as useLockBodyScroll,
  default as useLogger,
  default as useLongPress,
  default as useMap,
  default as useMedia,
  default as useMediaDevices,
  useMediatedState,
  default as useMethods,
  default as useMotion,
  default as useMount,
  default as useMountedState,
  default as useMouse,
  default as useMouseHovered,
  default as useMouseWheel,
  default as useNetwork,
  default as useNumber,
  default as useObservable,
  default as useOrientation,
  default as usePageLeave,
  default as usePermission,
  default as usePrevious,
  default as usePreviousDistinct,
  default as usePromise,
  default as useQueue,
  default as useRaf,
  default as useRafLoop,
  default as useRafState,
  default as useSearchParam,
  default as useScratch,
  default as useScroll,
  default as useScrolling,
  default as useSessionStorage,
  default as useSetState,
  default as useShallowCompareEffect,
  default as useSize,
  default as useSlider,
  default as useSpeech,
  default as useStartTyping,
  useStateWithHistory,
  default as useStateList,
  default as useThrottle,
  default as useThrottleFn,
  default as useTimeout,
  default as useTimeoutFn,
  default as useTitle,
  default as useToggle,
  default as useTween,
  default as useUnmount,
  default as useUnmountPromise,
  default as useUpdate,
  default as useUpdateEffect,
  default as useUpsert,
  default as useVibrate,
  default as useVideo,
  default as useStateValidator,
  useScrollbarWidth,
  useMultiStateValidator,
  default as useWindowScroll,
  default as useWindowSize,
  default as useMeasure,
  useRendersCount,
  useFirstMountState,
  default as useSet,
  createGlobalState,
  useHash,
} from 'react-use';
// not exported because of peer dependency
// export { default as useKeyboardJs } from 'react-use';
// not exported because of peer dependency
// export { default as useSpring } from 'react-use';

export {
  useIsPhoneX
}
